apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uvt1omw51-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uvt1omw51-go 
  name: uvt1omw51-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: uvt1omw51-go 
